#!/bin/sh
echo "removing KravenHD Skin"
rm -rf /usr/share/enigma2/KravenHD > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Converter/kraven* > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/KravenHD > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Renderer/kraven > /dev/null 2>&1
exit 0
