#!/bin/sh
echo "removing KravenHD Skin"
rm -rf /usr/share/enigma2/KravenHD > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Converter/kraven* > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/KravenHD > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Renderer/kraven > /dev/null 2>&1
opkg remove --force-depends enigma2-plugin-systemplugins-weathercomponenthandler
opkg remove --force-depends enigma2-plugin-systemplugins-extnumberzap
opkg remove --force-depends enigma2-plugin-extensions-weatherplugin
opkg remove --force-depends enigma2-plugin-skincomponents-weathercomponent
exit 0
