#!/bin/sh
echo "removing RevolutionBlack2 Skin"
rm -rf /usr/local/share/enigma2/RevolutionBlack2 > /dev/null 2>&1
mv /usr/local/share/enigma2/HDMUSkin/menu/menubg.png.original /usr/local/share/enigma2/HDMUSkin/menu/menubg.png
exit 0
