#!/bin/sh
echo "removing dreammmhd Skin"
rm -rf /usr/local/share/enigma2/shockstyleHD > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Renderer/NextEventName.pyo > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Renderer/NextEventTimeDuration.pyo > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Renderer/ShockstyleHDChNumber.pyo > /dev/null 2>&1
exit 0
